### ISSUE TITLE
Open console gesture issue on ios after modify CVar dialog, Unity 5.5.2p3

### ISSUE THREAD

**Issue by eandropov** [SpaceMadness/lunar-unity-console#46] opened 2017-03-27 10:55 UTC
Hello there, i have some strange issue on ios.
To reproduce it just create an empty scene with lunar console prefab, create some CVars, then build it to ios device. When i open and close modify value native dialog by pressing some CVar value in a right tab of lunar console, console won't open again by default 2 fingers down gesture. I found it only on ios, android build works fine. How can i fix that?

**Comment by weeeBox** [comment] 2017-03-27 15:36
Hey there.

Sorry about the issue. Would you be able to get logs from a device and send it to me?

Thanks,

-Alex

**Comment by weeeBox** [comment] 2017-03-27 16:55
@eandropov, I'm able to reproduce the issue and working on it now. Thanks, for reporting and sorry for the inconvenience.

**Comment by weeeBox** [comment] 2017-03-27 18:04
@eandropov, the issue is now fixed. I'm preparing an update for the package (would probably go live later this week). In a mean time, you can fix it in your project by updating the following file: `Assets/LunarConsole/Editor/iOS/Common/Console/Plugin/LUConsolePlugin.m`.

Reference commit: [4da7d2785a64ca9f243ac889d41a9ee54e3c4dcb](https://github.com/SpaceMadness/lunar-unity-console/pull/47/commits/4da7d2785a64ca9f243ac889d41a9ee54e3c4dcb)

Please, let me know if it works for you

**Closed by weeeBox** 2017-03-27 18:04 UTC
